@startuml

[*]-> ストップウォッチ

state ストップウォッチ {
[*] -> 停止
停止 --> 測定中 : スタートボタン
測定中 --> 停止 : ストップボタン
測定中 --> 測定中 : スプリットボタン
時間表示 --> ゼロ表示 : リセットボタン
--
[*] -> 通知ダイアログ非表示
通知ダイアログ非表示 --> 通知ダイアログ表示 : 通知ボタン
通知ダイアログ表示 --> 通知ダイアログ非表示 : 閉じるボタン
}

@enduml